version: '3'
services:
    web:
        restart: always
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
        links:
            - db
    php:
        image: php:7.4-fpm
        volumes:
            - ./app:/app
        build:
             dockerfile: Dockerfile
        links:
            - db

    db:
        image: mysql:latest
        container_name: db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=training_nfq
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=password
            - MYSQL_TCP_PORT=3306
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./docker-init-queries.sql:/docker-entrypoint-initdb.d/init.sql

    phpmyadmin:
        container_name: phpMyAdmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "9080:80"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - PMA_HOST=db